import 'package:flutter/material.dart';
import 'package:voc_app/src/common/constants/sizes.dart';

const gapW1 = SizedBox(width: Sizes.p1);
const gapW2 = SizedBox(width: Sizes.p2);
const gapW3 = SizedBox(width: Sizes.p3);
const gapW4 = SizedBox(width: Sizes.p4);
const gapW5 = SizedBox(width: Sizes.p5);
const gapW6 = SizedBox(width: Sizes.p6);
const gapW7 = SizedBox(width: Sizes.p7);
const gapW8 = SizedBox(width: Sizes.p8);
const gapW9 = SizedBox(width: Sizes.p9);
const gapW10 = SizedBox(width: Sizes.p10);
const gapW15 = SizedBox(width: Sizes.p15);
const gapW16 = SizedBox(width: Sizes.p16);

const gapH1 = SizedBox(height: Sizes.p1);
const gapH2 = SizedBox(height: Sizes.p2);
const gapH3 = SizedBox(height: Sizes.p3);
const gapH4 = SizedBox(height: Sizes.p4);
const gapH5 = SizedBox(height: Sizes.p5);
const gapH6 = SizedBox(height: Sizes.p6);
const gapH7 = SizedBox(height: Sizes.p7);
const gapH8 = SizedBox(height: Sizes.p8);
const gapH9 = SizedBox(height: Sizes.p9);
const gapH10 = SizedBox(height: Sizes.p10);
const gapH15 = SizedBox(height: Sizes.p15);
const gapH16 = SizedBox(height: Sizes.p16);

const expandW1 = Expanded(child: gapW1);
const expandW2 = Expanded(child: gapW2);
const expandW3 = Expanded(child: gapW3);
const expandW4 = Expanded(child: gapW4);
const expandW5 = Expanded(child: gapW5);
const expandW6 = Expanded(child: gapW6);
const expandW7 = Expanded(child: gapW7);
const expandW8 = Expanded(child: gapW8);
const expandW9 = Expanded(child: gapW9);
const expandW10 = Expanded(child: gapW10);

const expandH1 = Expanded(child: gapH1);
const expandH2 = Expanded(child: gapH2);
const expandH3 = Expanded(child: gapH3);
const expandH4 = Expanded(child: gapH4);
const expandH5 = Expanded(child: gapH5);
const expandH6 = Expanded(child: gapH6);
const expandH7 = Expanded(child: gapH7);
const expandH8 = Expanded(child: gapH8);
const expandH9 = Expanded(child: gapH9);
const expandH10 = Expanded(child: gapH10);
